[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = ["src/**"]

[build.environment]
  DB_HOST = "bxvl0imfammnkqd6ju3q-mysql.services.clever-cloud.com"
  DB_PORT = "3306"
  DB_USER = "ufkqa8gukkjv6agu"
  DB_PASSWORD = "DqZHDkL55PlXyV3OX0Fh"
  DB_NAME = "bxvl0imfammnkqd6ju3q"

[functions.environment]
  DB_HOST = "bxvl0imfammnkqd6ju3q-mysql.services.clever-cloud.com"
  DB_PORT = "3306"
  DB_USER = "ufkqa8gukkjv6agu"
  DB_PASSWORD = "DqZHDkL55PlXyV3OX0Fh"
  DB_NAME = "bxvl0imfammnkqd6ju3q"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
